from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_report(profile, symptoms, predictions, severity, diet, session_id):
    os.makedirs('reports', exist_ok=True)
    filename = f"reports/health_report_{session_id[:8]}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('Title', fontSize=22, fontName='Helvetica-Bold',
                                  textColor=colors.HexColor('#2196F3'), spaceAfter=10, alignment=1)
    story.append(Paragraph("🏥 AI Health Report", title_style))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", 
                           ParagraphStyle('sub', fontSize=10, textColor=colors.grey, alignment=1)))
    story.append(Spacer(1, 20))

    # Patient Info
    heading = ParagraphStyle('Heading', fontSize=14, fontName='Helvetica-Bold',
                              textColor=colors.HexColor('#1565C0'), spaceAfter=8)
    story.append(Paragraph("👤 Patient Information", heading))
    patient_data = [
        ['Name', profile.get('name', 'N/A')],
        ['Age', str(profile.get('age', 'N/A'))],
        ['Gender', profile.get('gender', 'N/A')],
    ]
    table = Table(patient_data, colWidths=[2*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#E3F2FD')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 15))

    # Symptoms
    story.append(Paragraph("🤒 Reported Symptoms", heading))
    symptoms_text = " • ".join(symptoms) if symptoms else "No symptoms recorded"
    story.append(Paragraph(symptoms_text, styles['Normal']))
    story.append(Spacer(1, 15))

    # Predictions
    story.append(Paragraph("🩺 Disease Predictions", heading))
    pred_data = [['Disease', 'Probability']]
    for p in predictions:
        pred_data.append([p['disease'], f"{p['probability']}%"])
    pred_table = Table(pred_data, colWidths=[4*inch, 2*inch])
    pred_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1565C0')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F5F5F5')]),
    ]))
    story.append(pred_table)
    story.append(Spacer(1, 15))

    # Severity
    story.append(Paragraph("⚠️ Severity Level", heading))
    sev_color = {'Mild': '#4CAF50', 'Moderate': '#FF9800', 'Severe': '#F44336'}
    color = sev_color.get(severity.get('label', 'Moderate'), '#FF9800')
    sev_style = ParagraphStyle('sev', fontSize=13, fontName='Helvetica-Bold',
                                textColor=colors.HexColor(color))
    story.append(Paragraph(f"{severity.get('label', 'N/A')} — {severity.get('action', '')}", sev_style))
    story.append(Spacer(1, 15))

    # Diet Plan
    story.append(Paragraph("🥗 Personalized Diet Plan", heading))
    story.append(Paragraph("✅ Foods to Eat:", 
                           ParagraphStyle('sub2', fontSize=11, fontName='Helvetica-Bold', textColor=colors.green)))
    for food in diet.get('foods_to_eat', []):
        story.append(Paragraph(f"  • {food}", styles['Normal']))
    story.append(Spacer(1, 8))
    story.append(Paragraph("❌ Foods to Avoid:", 
                           ParagraphStyle('sub3', fontSize=11, fontName='Helvetica-Bold', textColor=colors.red)))
    for food in diet.get('foods_to_avoid', []):
        story.append(Paragraph(f"  • {food}", styles['Normal']))
    story.append(Spacer(1, 15))

    # Disclaimer
    disc_style = ParagraphStyle('disc', fontSize=9, textColor=colors.grey, 
                                 borderColor=colors.grey, borderWidth=1, 
                                 borderPadding=8, backColor=colors.HexColor('#FFF9C4'))
    story.append(Paragraph("⚠️ DISCLAIMER: This report is generated by an AI system for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified doctor.", disc_style))

    doc.build(story)
    return filename